[package]
name = "byrdocs-tui"
version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
init = { path = "../init", version = "0.1.0" }
config = { path = "../config", version = "0.1.0" }
